pygments: true
permalink: none
markdown: redcarpet
language: "en"

#multilingual
languages:
  - {
      name: "Français", code: "fr", url: "/fr", sidebar:
      [
        { name: "Bienvenue", sidebar_name: "welcome", url: "/fr/index.html" },
        { name: "Installation", sidebar_name: "installation", url: "/fr/documentation/installation.html" },
        { name: "Configuration", sidebar_name: "configuration", url: "/fr/documentation/configuration.html" },
        { name: "Contribuer", sidebar_name: "contribute", url: "/fr/documentation/contribuer.html" },
        { name: "Modules", sidebar_name: "plugin", subsections: [
           { name: "Débuter", sidebar_name: "plugin_index", url: "/fr/documentation/modules/index.html" }
          ]
        }
      ]
    }
  - {
      name: "English", code: "en", url: "/", sidebar:
      [
        { name: "Welcome", sidebar_name: "welcome", url: "/index.html" },
        { name: "Installation", sidebar_name: "installation", url: "/en/documentation/installation.html" },
        { name: "Configuration", sidebar_name: "configuration", url: "/en/documentation/configuration.html" },
        { name: "Contribute", sidebar_name: "contribute", url: "/en/documentation/contribute.html" },
        { name: "Development", sidebar_name: "development", subsections:
          [
            { name: "Types", sidebar_name: "development_types", url: "/en/documentation/development/types/index.html" },
            { name: "Events", sidebar_name: "development_events", url: "/en/documentation/development/events/index.html" }
          ]
        },
        { name: "Features", sidebar_name: "features", subsections:
          [
            { name: "Coupons", sidebar_name: "features_coupons", subsections:
              [
               { name: "About coupons", sidebar_name: "features_coupons_index", url: "/en/documentation/features/coupons/index.html" },
               { name: "Effects", sidebar_name: "features_coupons_effects", url: "/en/documentation/features/coupons/effects.html" },
               { name: "Conditions", sidebar_name: "features_coupons_conditions", url: "/en/documentation/features/coupons/conditions.html" }
              ]
            },
            { name: "Administration permissions", sidebar_name: "features_permissions", subsections:
              [
               { name: "Administrators and profiles", sidebar_name: "features_permissions_admin", url: "/en/documentation/features/permissions/admin.html" },
               { name: "Permissions in modules", sidebar_name: "features_permissions_module", url: "/en/documentation/features/permissions/module.html" }
              ]
            },
            { name: "Tax engine", sidebar_name: "features_tax", subsections:
              [
               { name: "Manage taxes", sidebar_name: "features_tax_admin", url: "/en/documentation/features/tax/admin.html" },
               { name: "Tax type", sidebar_name: "features_tax_type", url: "/en/documentation/features/tax/type.html" }
              ]
            }
          ]
        },
        { name: "Modules", sidebar_name: "plugin", subsections: [
           { name: "Starting", sidebar_name: "plugin_index", url: "/en/documentation/modules/index.html" },
           { name: "Payment module", sidebar_name: "plugin_payment", url: "/en/documentation/modules/payment.html" },
           { name: "Delivery module", sidebar_name: "plugin_delivery", url: "/en/documentation/modules/delivery.html" },
           { name: "Loops", sidebar_name: "plugin_loop", url: "/en/documentation/modules/loops.html" },
           { name: "Actions", sidebar_name: "plugin_action", url: "/en/documentation/modules/actions.html" },
           { name: "Commands", sidebar_name: "plugin_command", url: "/en/documentation/modules/commands.html" },
           { name: "Routing", sidebar_name: "plugin_routing", url: "/en/documentation/modules/routing.html" },
           { name: "Admin hooks", sidebar_name: "plugin_hook", url: "/en/documentation/modules/hook.html" }
          ]
        },
        { name: "Form", sidebar_name: "form", subsections: [
            { name: "Program you Form", sidebar_name: "form_index", url: "/en/documentation/form/index.html" },
            { name: "Use your form in actions", sidebar_name: "form_action", url: "/en/documentation/form/action.html" },
            { name: "Display form", sidebar_name: "form_template", url: "/en/documentation/form/template.html" },
            { name: "Forms available in Thelia", sidebar_name: "form_list", subsections: [
                {name: "Customer create account", sidebar_name: "form_list_customercreate", url: "/en/documentation/form/list/customer_create.html"},
                {name: "Customer update profile", sidebar_name: "form_list_customer_updateprofile", url: "/en/documentation/form/list/customer_profile_update.html"},
                {name: "Customer login", sidebar_name: "form_list_customerlogin", url: "/en/documentation/form/list/customer_login.html"},
                {name: "Customer password recovery", sidebar_name: "form_list_customerpassword", url: "/en/documentation/form/list/customer_lost_password.html"},
                {name: "Customer password update", sidebar_name: "form_list_updatepassword", url: "/en/documentation/form/list/customer_password_update.html"},
                {name: "Customer address creation", sidebar_name: "form_list_addresscreate", url: "/en/documentation/form/list/customer_address_create.html"},
                {name: "Customer address update", sidebar_name: "form_list_addressupdate", url: "/en/documentation/form/list/customer_address_update.html"},
                {name: "Contact", sidebar_name: "form_list_contact", url: "/en/documentation/form/list/contact.html"},
                {name: "Newsletter subscription", sidebar_name: "form_list_newsletter", url: "/en/documentation/form/list/newsletter.html"},
                {name: "Add to cart", sidebar_name: "form_list_cartadd", url: "/en/documentation/form/list/cart_add.html"},
                {name: "Order delivery", sidebar_name: "form_list_orderdelivery", url: "/en/documentation/form/list/order_delivery.html"},
                {name: "Order payment", sidebar_name: "form_list_orderpayment", url: "/en/documentation/form/list/order_payment.html"},
                {name: "Coupon", sidebar_name: "form_list_coupon", url: "/en/documentation/form/list/coupon.html"}
              ]
            }
          ]
        },
        { name: "Loops", sidebar_name: "loop", subsections: [
            { name: "About loops", sidebar_name: "loop_index", url: "/en/documentation/loop/index.html" },
            { name: "Accessory loop", sidebar_name: "loop_accessory", url: "/en/documentation/loop/accessory.html" },
            { name: "Address loop", sidebar_name: "loop_address", url: "/en/documentation/loop/address.html" },
            { name: "Admin loop", sidebar_name: "loop_admin", url: "/en/documentation/loop/admin.html" },
            { name: "Area loop", sidebar_name: "loop_area", url: "/en/documentation/loop/area.html" },
            { name: "Associated content loop", sidebar_name: "loop_associated_content", url: "/en/documentation/loop/associated_content.html" },
            { name: "Attribute loop", sidebar_name: "loop_attribute", url: "/en/documentation/loop/attribute.html" },
            { name: "Attribute availability loop", sidebar_name: "loop_attribute_availability", url: "/en/documentation/loop/attribute_availability.html" },
            { name: "Attribute combination", sidebar_name: "loop_attribute_combination", url: "/en/documentation/loop/attribute_combination.html" },
            { name: "Auth loop", sidebar_name: "loop_auth", url: "/en/documentation/loop/auth.html" },
            { name: "Cart loop", sidebar_name: "loop_cart", url: "/en/documentation/loop/cart.html" },
            { name: "Category loop", sidebar_name: "loop_category", url: "/en/documentation/loop/category.html" },
            { name: "Category path loop", sidebar_name: "loop_category_path", url: "/en/documentation/loop/category_path.html" },
            { name: "Category tree loop", sidebar_name: "loop_category_tree", url: "/en/documentation/loop/category_tree.html" },
            { name: "Config loop", sidebar_name: "loop_config", url: "/en/documentation/loop/config_loop.html" },
            { name: "Content loop", sidebar_name: "loop_content", url: "/en/documentation/loop/content.html" },
            { name: "Country loop", sidebar_name: "loop_country", url: "/en/documentation/loop/country.html" },
            { name: "Currency loop", sidebar_name: "loop_currency", url: "/en/documentation/loop/currency.html" },
            { name: "Customer loop", sidebar_name: "loop_customer", url: "/en/documentation/loop/customer.html" },
            { name: "Delivery loop", sidebar_name: "loop_delivery", url: "/en/documentation/loop/delivery.html" },
            { name: "Document loop", sidebar_name: "loop_document", url: "/en/documentation/loop/document.html" },
            { name: "Feature loop", sidebar_name: "loop_feature", url: "/en/documentation/loop/feature.html" },
            { name: "Feature availability loop", sidebar_name: "loop_feature_availability", url: "/en/documentation/loop/feature_availability.html" },
            { name: "Feature value loop", sidebar_name: "loop_feature_value", url: "/en/documentation/loop/feature_value.html" },
            { name: "Folder loop", sidebar_name: "loop_folder", url: "/en/documentation/loop/folder.html" },
            { name: "Folder path loop", sidebar_name: "loop_folder_path", url: "/en/documentation/loop/folder_path.html" },
            { name: "Folder tree loop", sidebar_name: "loop_folder_tree", url: "/en/documentation/loop/folder_tree.html" },
            { name: "Image loop", sidebar_name: "loop_image", url: "/en/documentation/loop/image.html" },
            { name: "Lang loop", sidebar_name: "loop_lang", url: "/en/documentation/loop/lang.html" },
            { name: "Module loop", sidebar_name: "loop_module", url: "/en/documentation/loop/module.html" },
            { name: "Order loop", sidebar_name: "loop_order", url: "/en/documentation/loop/order.html" },
            { name: "Order address loop", sidebar_name: "loop_order_address", url: "/en/documentation/loop/order_address.html" },
            { name: "Order coupon loop", sidebar_name: "loop_order_coupon", url: "/en/documentation/loop/order_coupon.html" },
            { name: "Order product loop", sidebar_name: "loop_order_product", url: "/en/documentation/loop/order_product.html" },
            { name: "Order product attribute combination loop", sidebar_name: "loop_order_product_attribute_combination", url: "/en/documentation/loop/order_product_attribute_combination.html" },
            { name: "Order status loop", sidebar_name: "loop_order_status", url: "/en/documentation/loop/order_status.html" },
            { name: "Payment loop", sidebar_name: "loop_payment", url: "/en/documentation/loop/payment.html" },
            { name: "Product loop", sidebar_name: "loop_product", url: "/en/documentation/loop/product.html" },
            { name: "Product sale elements loop", sidebar_name: "loop_product_sale_elements", url: "/en/documentation/loop/product_sale_elements.html" },
            { name: "Tax loop", sidebar_name: "loop_tax", url: "/en/documentation/loop/tax.html" },
            { name: "TaxRule loop", sidebar_name: "loop_tax_rule", url: "/en/documentation/loop/tax_rule.html" },
            { name: "Title loop", sidebar_name: "loop_title", url: "/en/documentation/loop/title.html" }
          ]
        },
        { name: "Substitutions", sidebar_name: "substitution", subsections: [
            { name: "Category", sidebar_name: "substitution_category", url: "/en/documentation/substitutions/category.html" },
            { name: "Content", sidebar_name: "substitution_content", url: "/en/documentation/substitutions/content.html" },
            { name: "Customer", sidebar_name: "substitution_customer", url: "/en/documentation/substitutions/customer.html" },
            { name: "Folder", sidebar_name: "substitution_folder", url: "/en/documentation/substitutions/folder.html" },
            { name: "Product", sidebar_name: "substitution_product", url: "/en/documentation/substitutions/product.html" }
          ]
        },
        { name: "Templates", sidebar_name: "templates", subsections: [
            { name: "Introduction", sidebar_name: "templates_introduction", url: "/en/documentation/templates/introduction.html" },
            { name: "Contents", sidebar_name: "templates_contents", url: "/en/documentation/templates/content.html" },
            { name: "Assets management", sidebar_name: "templates_assets", url: "/en/documentation/templates/assets.html" },
            { name: "Internationalization", sidebar_name: "templates_i18n", url: "/en/documentation/templates/i18n.html" }
          ]
        }
      ]
    }
